config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'posts#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  post   '/like/:post_id' => 'likes#like',   as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
  resources :relationships, only: [:create, :destroy]
  resources :meals
  resources :rankings, only: [:index, :show]
  resources :notifications, only: [:index]


  resources :posts do
    resources :comments
    resources :users, only: [:index, :show]
    collection do
      get 'search'
      get 'about'
      get 'usage'
      get 'notice'
      get 'tab'
    end
  end

end

app/views/layouts/shared/_flash.html.erb
<div class='flash'>
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: key %>
  <% end %>
</div>

app/views/layouts/shared/_footer.html.erb
<footer class='footer-main'>
  <div class='footer-list'>
    <%= link_to tab_posts_path, class:'footer-list__link' do %>
      <div class='footer-list__information'>このサイトについて</div>
    <% end %>
    <%= link_to root_path, class:'footer-list__link' do %>
      <div class='footer-list__information'>ホームへ戻る</div>
    <% end %>
  </div>
  <div class='footer-main__copyright'>
    <a>Copyright（C） 2019　kohei sugawara All Rights Reserved.</a>
  </div>
</footer>

app/views/layouts/shared/_header.html.erb
<header class='header-main'>
  <div class='logo'>
    <%= link_to root_path, class:'logo__root-path' do %>
      <p class="animation_07">岳人</p>
    <% end %>
    <div id='nav-container'>
      <div class='toggle-icon'>
        <span class='bar'></span>
        <span class='bar'></span>
        <span class='bar'></span>
      </div>
    </div>
  </div>
  <h3 class='header-main__logo-txt'>大好きな山や山メシをシェアしよう</h3>
  <div class='header-main__search'>
    <%= search_form_for @search, url:search_posts_path do |f| %>
      <i class='fa fa-chevron-down'></i>
      <%= f.collection_select :prefecture_id_eq, Prefecture.all, :id, :name, {prompt: "都道府県"} %>
      <%= f.search_field :name_or_text_cont, class: 'header-main__search__text', placeholder: '山の名前を検索' %>
      <%= f.submit '検索', class:'header-main__search__btn' %>
    <% end %>
  </div>
</header>
<%= render 'users/shared/login-header' %>

app/views/layouts/shared/_sp-banner.html.erb
<div class='sp-banner'>
  <div class='sp-banner__icon'>
    <%= link_to root_path do %>
      <i class='fas fa-sticky-note fa-3x'></i>
    <% end %>
    <%= link_to meals_path do %>
      <i class='fas fa-hamburger fa-3x'></i>
    <% end %>
    <%= link_to users_path do %>
      <i class='fas fa-users fa-3x'></i>
    <% end %>
    <%= link_to rankings_path do %>
      <i class='fas fa-heart fa-3x'></i>
    <% end %>
    <%= link_to search_posts_path do %>
      <i class='fa fa-search fa-3x'></i>
    <% end %>
  </div>
</div>

app/views/layouts/shared/_sp-button.html.erb
<% if user_signed_in? %>
  <%=link_to new_post_path, class:'sp-footer-btn' do %>
    <i class='far fa-paper-plane fa-3x'></i>
  <% end %>
<% end %>

app/views/layouts/shared/_sp-header.html.erb
<header class='sp-header-main'>
  <div id='nav-drawer'>
    <%= link_to root_path, class:'logo-box' do %>
      <h1 class='logo-box__sp-logo'>岳人</h1>
      <h3 class='logo-box__sp-kana'>〜たけと〜</h3>
    <% end %>
    <%= link_to @user do %>
      <%= sp_header_login_image %>
    <% end %>
    <%# チェックボックス。常に非表示。 %>
    <input id='nav-input' type='checkbox' class='nav-unshown'>
    <%# チェックボックスのラベル。ここで三アイコンを表示。タップによりinputがチェック状態に。 %>
    <label id='nav-open' for='nav-input'><span></span></label>
    <%# チェックボックスのラベルその2。はじめは非表示。inputがチェック状態になると薄黒のカバーとして表示。 %>
    <%# タップによりinputのチェック解除。 %>
    <label class='nav-unshown' id='nav-close' for='nav-input'></label>
    <%# 表示される中身。inputのチェックの有無に連動して表示<=>非表示に。 %>
    <div id='nav-content'>
      <% if user_signed_in? %>
        <h2 class='sidebar__user-name'>こんにちは！<%= current_user.nickname %>さん！</h2>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'sidebar__user-link' %>
        <%= link_to 'プロフィール変更', edit_user_registration_path, class:'sidebar__user-link' %>
        <div class='sidebar__count'>
          登った山は<%= current_user.posts.count %>ヶ所です！
        </div>
        <%= render 'users/shared/stats' %>
      <% else %>
        <h2 class='sidebar__user-name'>こんにちは！ユーザーさん！</h2>
        <h2 class='sidebar__login-text'>まずはログインしよう！</h2>
        <%= link_to 'ログイン', new_user_session_path, class:'sidebar__user-link' %>
        <%= link_to '新規登録', new_user_registration_path, class:'sidebar__user-link' %>
      <% end %>
      <div class='site-list'>
        <%= link_to about_posts_path, class:'site-list__link' do %>
          <div class='site-list__information'>このサイトについて</div>
        <% end %>
        <%= link_to usage_posts_path, class:'site-list__link' do %>
          <div class='site-list__information'>使い方</div>
        <% end %>
        <%= link_to notice_posts_path, class:'site-list__link' do %>
          <div class='site-list__information'>お知らせ</div>
        <% end %>
      </div>
      <div class='site-main__copyright'>
        <a>Copyright（C） 2019　kohei sugawara All Rights Reserved.</a>
      </div>
    </div>
  </div>
</header>

app/views/layouts/shared/_validation-message.html.erb
<% if @post.errors.any? %>
  <ul>
    <% @post.errors.full_messages.each do |message|%>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>