config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'posts#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  post   '/like/:post_id' => 'likes#like',   as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
  resources :relationships, only: [:create, :destroy]
  resources :meals
  resources :rankings, only: [:index, :show]
  resources :notifications, only: [:index]


  resources :posts do
    resources :comments
    resources :users, only: [:index, :show]
    collection do
      get 'search'
      get 'about'
      get 'usage'
      get 'notice'
      get 'tab'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts,    dependent: :destroy
  has_many :meals,    dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes,    dependent: :destroy
  has_many :like_posts, through: :likes, source: :post

  before_save   :downcase_email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email,     presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :nickname,  presence: true, length: {maximum: 20}
  validates :profile,   presence: true

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  mount_uploader :image, ImageUploader

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  def downcase_email
    self.email.downcase!
  end

  def create_notification_follow!(current_user)
    temp = Notification.includes(:visited).where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :following, :followers]

  def index
    @users = User.order('updated_at DESC')
  end

  def show
    @meals = @user.meals.order("created_at DESC")
    @posts = @user.posts.order("created_at DESC").page(params[:page]).per(5)
  end

  def following
    @title = "フォロー 一覧"
    @users = @user.following.page(params[:page]).per(10)
    render 'show-follow'
  end

  def followers
    @title = "フォロワー 一覧"
    @users = @user.followers.page(params[:page]).per(10)
    render 'show-follow'
  end

  private

  def set_user
    @user  = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_login-header.html.erb
<div class='mypage-header'>
  <div id="nav-toggle">
    <div>
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>
  <div id="gloval-nav">
    <% if signed_in? %>
      <nav>
        <ul>
          <li><%=link_to 'Home', root_path %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <li><%= link_to 'マイページ', current_user %></li>
          <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
          <li><%= link_to '登った山とメシを投稿', new_post_path %></li>
          <li><%= link_to 'お知らせ', notifications_path %></li>
        </ul>
      </nav>
    <%else %>
      <nav>
        <ul>
          <li><%= link_to 'ログイン', new_user_session_path %></li>
          <li><%= link_to '新規登録', new_user_registration_path %></li>
        </ul>
      </nav>
    <% end %>
  </div>
  <h2 class='mypage-header__text'>岳人</h2>
  <h3 class='mypage-header__kana'>〜たけと〜</h3>
  <div class='wrapper'>
    <div class='icon-search-container' data-ic-class='search-trigger'>
      <span class='fa fa-search'></span>
      <%= search_form_for @search, url:search_posts_path do |f| %>
        <%= f.search_field :name_or_text_cont, class:'search-input', placeholder:'search' %>
        <%= f.submit '検索', type:'hidden' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/shared/_stats.html.erb
<% @user ||= current_user %>
<div class='follow-box'>
  <%= link_to following_user_path(@user),class:'follow-box__link' do %>
    <div id='following' class='follow-box__follower'>
      <%= @user.following.count %>
    </div>
    フォロー中
  <% end %>
  <%= link_to followers_user_path(@user), class:'follow-box__link' do %>
    <div id='followers' class='follow-box__follower'>
      <%= @user.followers.count %>
    </div>
    フォロワー
  <% end %>
</div>