config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'posts#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  post   '/like/:post_id' => 'likes#like',   as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
  resources :relationships, only: [:create, :destroy]
  resources :meals
  resources :rankings, only: [:index, :show]
  resources :notifications, only: [:index]


  resources :posts do
    resources :comments
    resources :users, only: [:index, :show]
    collection do
      get 'search'
      get 'about'
      get 'usage'
      get 'notice'
      get 'tab'
    end
  end

end

app/models/notification.rb
class Notification < ApplicationRecord

  default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = current_user.passive_notifications.includes(:visitor, :visited, :post).page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>
<article class='notification-article'>
  <section class='notification-section-left'>
    <%= link_to user_path(visitor) do %>
      <%= notification_user_image(visitor) %>
    <% end %>
  </section>
  <section class='notification-section-right'>
    <div class='notification-section-right__content'>
      <%= link_to user_path(visitor), class:'notification-section-right__content__link'  do %>
        <strong><%= visitor.nickname %></strong>
      <% end %>
        さんが
      <% case notification.action when 'follow' %>
          あなたを
          <p class='notification-section-right__content__text-bold'>
            フォロー
          </p>
          しました!
        <% when 'like' then %>
          <%= link_to 'あなたの投稿', notification.post, class:'notification-section-right__content__link' %>
          に
          <p class='notification-section-right__content__text-bold'>
            いいね!
          </p>
          しました!
        <% when 'comment' then %>
          <% if notification.post.user_id == visited.id %>
            <%= link_to 'あなたの投稿', notification.post, class:'notification-section-right__content__link' %>
          <%else%>
            <%= link_to post_path(notification.post) do %>
              <strong><%= notification.post.user.nickname %>さんの投稿</strong>
            <% end %>
          <% end %>
          に
          <p class='notification-section-right__content__text-bold'>
            コメント
          </p>
          しました!
          <div class='notification-section-right__content__comment-text'>
            <p><%= Comment.find_by(id: notification.comment_id)&.text %></p>
          </div>
      <% end %>
      <div class='notification-section-right__content__time'>
        <p><%= time_ago_in_words(notification.created_at).upcase %></p>
      </div>
    </div>
  </section>
</article>

app/views/notifications/index.html.erb
<main>
  <%= render 'layouts/shared/header' %>
  <h1 class='notification-page'>お知らせ</h1>
  <% notifications = @notifications.where.not(visitor_id: current_user.id) %>
  <% if notifications.exists? %>
    <%= render notifications %>
    <%= paginate notifications %>
  <% else %>
    <p class='notification-article__text'>通知がありません</p>
  <% end %>
  <%= render 'layouts/shared/footer' %>
</main>