config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'posts#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  post   '/like/:post_id' => 'likes#like',   as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
  resources :relationships, only: [:create, :destroy]
  resources :meals
  resources :rankings, only: [:index, :show]
  resources :notifications, only: [:index]


  resources :posts do
    resources :comments
    resources :users, only: [:index, :show]
    collection do
      get 'search'
      get 'about'
      get 'usage'
      get 'notice'
      get 'tab'
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :user
  belongs_to_active_hash :prefecture
  has_many   :comments, dependent: :destroy
  has_many   :comment_users, through: :comments, source: :user
  has_many   :likes, dependent: :destroy
  has_many   :liking_users, through: :likes, source: :user
  has_one    :meal,  dependent: :destroy
  has_many   :notifications, dependent: :destroy
  accepts_nested_attributes_for :meal
  enum difficulty: [:challenge, :normal, :easy]
  mount_uploader :image, ImageUploader
  validates :name, :text, :prefecture, presence: true

  def self.create_all_ranks
    Post.find(Like.group(:post_id).order('count(post_id) DESC').limit(20).pluck(:post_id))
  end

  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @all_ranks = Post.includes(:user).create_all_ranks
    @posts = Post.includes(:user).order('updated_at DESC')
    @users = User.order('updated_at DESC')
    @meals = Meal.order('updated_at DESC')
    if user_signed_in?
      @current_user_posts=Post.includes(:user).where(user_id:current_user.id).order('updated_at DESC')
      @posts = Post.includes(:user).order('updated_at DESC')
    end
  end

  def show
    @post_show_title = "投稿詳細"
    @comments = @post.comments.includes(:user).last(5)
    @comment = Comment.new
  end

  def new
    @post_new_title = "新規投稿"
    @post = Post.new
    @post.build_meal
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      flash[:success] = "投稿が完了しました！"
      redirect_to :root
    else
      # flash.nowを使うシチュエーションは、リダイレクトをしない場合
      flash.now[:alert] = "投稿が失敗しました。"
      render :new
    end
  end

  def edit
    @post_edit_title = "投稿編集"
  end

  def update
    if @post.user_id == current_user.id
      sleep 1
      if @post.update(post_params)
        flash[:success] = "編集が完了しました！"
        redirect_to :root
      else
        flash.now[:alert] = '商品の編集に失敗しました'
        render :edit
      end
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = '商品を削除しました'
      redirect_to :root
    else
      flash.now[:alert] = '商品の削除に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  def notification
  end

  def usage
  end

  def notification
  end

  def ranking
    @all_ranks = Post.create_all_ranks
  end

  private
  def post_params
    params.require(:post).permit(
      :name,
      :text,
      :image,
      :elevation,
      :walking_distance,
      :difficulty,
      :prefecture_id,
      :remove_image,
      meal_attributes: [:id,
                        :name,
                        :image,
                        :cooking_time,
                        :food_stuff,
                        :cooking_method,
                        :user_id]
    ).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/views/posts/_header.html.erb
<header id="header-main">
  <div id="header">
    <h3 class="logo-txt">大好きな山や山メシをシェアしよう</h3>
    <div class="logo-box">
      <div class="logo">
        <%= link_to root_path, class:'root-path-logo' do %>
          <%= image_tag"初日の出のアイコン.png", class:'yama-icon' %>
          <h1 class="small-txt">岳人</h1>
        <% end %>
      </div>
    </div>
    <form id="search">
      <input type="text" class="search-txt" placeholder="山の名前を入力", name="query-search">
      <input type="submit" class="search-btn" value="検索">
    </form>
    <% if user_signed_in? %>
      <div id="mypage-header">
        <ul class="mypage-contents">
          <div class="link-reg">
            <i class="fa fa-mountain fa-2x"></i>
            <%= link_to "登った山を投稿", new_post_path, class:'mypage-box' %>
          </div>
          <div class="link-reg">
            <i class="fa fa-utensils fa-2x"></i>
            <%= link_to "山メシを投稿", {}, class:'mypage-box' %>
          </div>
          <div class="link-reg">
            <i class="far fa-user fa-2x"></i>
            <%= link_to "マイページ", {}, class:'mypage-box' %>
          </div>
          <div class="link-reg">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:'mypage-box' %>
          </div>
        </ul>
      </div>
      <% else %>
        <div id="mypage-header">
          <ul class="mypage-contents">
            <div class="link-reg">
              <%= link_to "ログイン", new_user_session_path, class: 'post', class:'mypage-box' %>
            </div>
            <div class="link-reg">
              <%= link_to "新規登録", new_user_registration_path, class: 'post', class:'mypage-box' %>
            </div>
          </ul>
        </div>
      <% end %>
  </div>
</header>

app/views/posts/about.html.erb
<% provide(:title, "このサイトについて") %>
<div class='sp-main'>
  <div class="detail-post-box">
    <div class="detail-post-container">
      <div class="detail-name">
        このアプリについて
      </div>
      <h2>概要</h2>
      <div class="detail-description">
        <div class="detail-display">
          山登りや山で食べるご飯(通称:山メシ)が好きな人たちが撮った写真や感想を投稿できるSNSアプリです！
        </div>
      </div>
      <h2>説明</h2>
      <div class="detail-description">
        <div class="detail-display">
          自分が撮った山での写真を共有しませんか？<br/>自分がまだ登った事ない山のリアルな口コミを知りたい！山メシがいつもワンパターンになってしまう...<br/>他のSNSアプリだと盛られた写真ばかりで非現実的だなと感じている山好きの方々の為のSNSアプリ！<br/>加工しないリアルな写真やお手軽な山メシを等身大の自分を表現できるアプリです！
        </div>
      </div>
      <h2>機能</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>写真・テキスト投稿・編集・削除</li>
          <li>投稿一覧</li>
          <li>いいね機能</li>
          <li>フォロー機能</li>
          <li>コメント投稿機能</li>
          <li>ユーザーログイン・ログアウト機能</li>
          <li>ユーザー情報編集・削除</li>
          <li>ユーザー 一覧</li>
          <li>投稿検索機能</li>
          <li>ランキング機能</li>
        </div>
      </div>
      <h2>備考</h2>
      <div class="detail-description">
        現在は以下の機能がまだ使えません。機能は随時、追加していきます。
        <div class="detail-display">
          <li>山メシ投稿の編集・削除</li>
        </div>
      </div>
      <h2>作者の自己紹介</h2>
      <div class="detail-description">
        <div class="detail-display">
          webエンジニアを目指し転職活動中です！<br/>2019年4月から小売業界で店長として働きながら半年間Ruby,Ruby on Railsを学習しています。
        </div>
      </div>
      <h2>SNS</h2>
      <div class="detail-description">
        <div class="detail-display">
          <%= link_to 'https://www.wantedly.com/users/120417283', target: :_blank do %>
            wantedly<br/>
          <% end %>
          <%= link_to 'https://twitter.com/suzy16676187', target: :_blank do %>
            twitter<br/>
          <% end %>
          <%= link_to 'https://qiita.com/suzy1031', target: :_blank do %>
            Qiita<br/>
          <% end %>
          <%= link_to 'https://suzyanamateurengineer.hatenablog.com/', target: :_blank do %>
            はてなブログ
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% provide(:title, @post_edit_title) %>
<main>
  <%= render 'layouts/shared/header' %>
  <%= render 'layouts/shared/flash' %>
  <%= render 'layouts/shared/validation-message' %>
  <div class='new-post-box'>
    <div class='new-post-box__container'>
      <%= render 'posts/partial/edit-post' %>
    </div>
  </div>
  <%= render 'layouts/shared/footer' %>
</main>


<div class='sp-main'>
  <%= render 'layouts/shared/sp-header' %>
  <div class='sp-new-box'>
    <%= render 'posts/partial/sp-edit-post' %>
  </div>
  <%= render 'layouts/shared/sp-banner' %>
</div>

app/views/posts/index.html.erb
<main>
  <%= render 'layouts/shared/header' %>
  <%= render 'layouts/shared/flash' %>

  <div class='large-container'>
    <%= render 'posts/partial/post-lists' %>
    <%= render 'users/user-lists' %>
    <%= render 'users/mypage-box' %>
  </div>

  <div id='main-container'>
    <h2 class='list-title'>人気投稿ランキング</h2>
      <ul class='horizontal-list'>
        <%= render 'posts/partial/ranking-lists' %>
      </ul>
    <%= render 'meals/partial/meshi-lists' %>
    <% if signed_in? && @user.posts.any? %>
      <h2 class='list-title'><%=current_user.nickname %>さんが登った山リスト</h2>
      <ul class='horizontal-list'>
        <%= render partial: 'posts/partial/yama-lists', collection: @current_user_posts, as:'post' %>
      </ul>
    <% else %>
      <%= render 'posts/partial/before-lists' %>
    <% end %>
  </div>

  <%= render 'layouts/shared/footer' %>

</main>

<%# スマホ用topページ %>
<div class='sp-main'>
  <%= render 'layouts/shared/sp-header' %>
  <h1 class='sp-top-home'>ホーム</h1>
  <div class='sp-list-box'>
    <%= render partial: 'posts/partial/sp-index', collection: @posts, as: :post %>
  </div>
  <%= render 'layouts/shared/sp-button' %>
  <%= render 'layouts/shared/sp-banner' %>
</div>

app/views/posts/new.html.erb
<% provide(:title, @post_new_title) %>
<main>
  <%= render 'layouts/shared/header' %>
  <%= render 'layouts/shared/flash' %>
  <%= render 'layouts/shared/validation-message' %>
  <div class='new-post-box'>
    <div class='new-post-box__container'>
      <%= render 'posts/partial/new-post' %>
    </div>
  </div>
  <%= render 'layouts/shared/footer' %>
</main>

<%# スマホ用ページ %>
<div class='sp-main'>
  <%= render 'layouts/shared/sp-header' %>
  <%= render 'layouts/shared/flash' %>
  <%= render 'layouts/shared/validation-message' %>
  <div class='sp-new-box'>
    <%= render 'posts/partial/sp-new-post' %>
  </div>
  <%= render 'layouts/shared/sp-banner' %>
</div>

app/views/posts/notice.html.erb
<% provide(:title, "お知らせ") %>
<div class='sp-main'>
  <%= render "layouts/shared/header" %>
  <div class="detail-post-box">
    <div class="detail-post-container">
      <div class="detail-name">
        お知らせ
      </div>
      <h2>2019.11.09</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>新規コメント投稿をajax化(PC版)</li>
        </div>
      </div>
      <h2>2019.10.30</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>コメント機能をスマホサイズでも利用できるように修正</li>
          <li>コメントの編集・削除機能を追加</li>
        </div>
      </div>
      <h2>2019.10.29</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>サインアップページをレスポンシブ化</li>
          <li>サインインページをレスポンシブ化</li>
          <li>ユーザー一覧ページをレスポンシブ化</li>
          <li>ユーザー詳細ページをレスポンシブ化</li>
        </div>
      </div>
      <h2>2019.10.26</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>投稿詳細ページをレスポンシブ化</li>
        </div>
      </div>
      <h2>2019.10.24</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>ランキングページをレスポンシブ化</li>
        </div>
      </div>
      <h2>2019.10.23</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>検索ページをレスポンシブ化</li>
          <li>投稿一覧ページをレスポンシブ化</li>
        </div>
      </div>
      <h2>2019.10.22</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>トップページをレスポンシブ化</li>
        </div>
      </div>
      <h2>2019.10.19</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>フォロー/フォロワー 一覧機能の実装</li>
        </div>
      </div>
      <h2>2019.10.18</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>投稿機能内で全角英数字が登録できないように修正</li>
          <li>emailは大文字英数字から小文字へ変換しDB保存するように設定</li>
        </div>
      </div>
      <h2>2019.10.17</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>Nginxアップロードの上限値を10Mに変更</li>
        </div>
      </div>
      <h2>2019.10.12</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>Capistranoを設定し自動デプロイ化</li>
          <li>画像をAWS S3に保存できるように設定</li>
        </div>
      </div>
      <h2>2019.10.11</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>AWSインスタンス作成</li>
          <li>Unicorn_rails,Nginx,MySQLを設定しデプロイ</li>
        </div>
      </div>
      <h2>2019.10.10</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>READMEの作成</li>
        </div>
      </div>
      <h2>2019.10.09</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>seedデータの作成</li>
          <li>ランキング機能の実装</li>
          <li>ユーザーアバター登録を実装</li>
          <li>nested modelを用いた投稿フォームを実装</li>
        </div>
      </div>
      <h2>2019.10.08</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>ユーザープロフィール欄の実装</li>
          <li>ユーザー詳細ページの実装</li>
          <li>gem 'kaminari'を用いたページネーションの実装</li>
          <li>フォロー機能の実装②</li>
        </div>
      </div>
      <h2>2019.10.07</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>gem 'ransack'を用いた検索機能の実装</li>
          <li>フォロー機能の実装①</li>
          <li>投稿詳細ページにユーザーのアバター表示実装</li>
        </div>
      </div>
      <h2>2019.10.06</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>いいね機能の実装②</li>
        </div>
      </div>
      <h2>2019.10.04</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>コメント投稿機能の実装</li>
          <li>いいね機能の実装①</li>
        </div>
      </div>
      <h2>2019.10.03</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>マイページボックスのマークアップ</li>
          <li>投稿の編集機能の実装</li>
          <li>ログイン時のバリデーション設定</li>
          <li>ユーザー削除・編集機能の実装</li>
        </div>
      </div>
      <h2>2019.10.02</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>gem 'devise'用いたサインアップ・ログイン機能</li>
          <li>サインアップ・ログイン画面のマークアップ</li>
          <li>ログインユーザーの投稿一覧を表示</li>
          <li>全ユーザーの投稿一覧を表示</li>
          <li>投稿削除機能の実装</li>
          <li>JavaScriptを使い画像のプレビュー表示イベント実装</li>
        </div>
      </div>
      <h2>2019.10.01</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>投稿詳細ページのマークアップ</li>
          <li>投稿完了時のflash実装</li>
        </div>
      </div>
      <h2>2019.09.30</h2>
      <div class="detail-description">
        <div class="detail-display">
          <li>トップページのマークアップ</li>
          <li>新規投稿機能の実装</li>
        </div>
      </div>
    </div>
  </div>
  <%= render "layouts/shared/footer" %>
</div>

app/views/posts/search.html.erb
<main>
  <%= render 'layouts/shared/header' %>
  <% if @search_result.present? %>
    <div class='search-result'>
      <h2 class='search-result__title'>検索結果{ <%= @search_result.total_count %>件 }</h2>
        <div class='search-result__count'>
          <%= @search_result.current_page %>/<%= @search_result.total_pages %>ページ
        </div>
        <div class='search-container'>
          <%= render partial: 'posts/partial/yama-lists', collection: @search_result, as:'post'%>
        </div>
        <%= paginate @search_result %>
    </div>
  <% else %>
    <div class='search-result'>
      <h2 class='search-result__title'>該当する投稿が見つかりません。</h2>
    </div>
  <% end %>
  <%= render 'layouts/shared/footer' %>
</main>

<%# スマホ用searchページ %>
<div class='sp-main'>
  <%= render 'layouts/shared/sp-header' %>
  <div class='sp-search'>
    <%= search_form_for @search, url:search_posts_path do |f| %>
      <%= f.collection_select :prefecture_id_eq, Prefecture.all, :id, :name, {prompt: '都道府県'} %>
      <%= f.search_field :name_or_text_cont, class: 'sp-search__box', placeholder: '山の名前を検索' %>
      <%= f.submit '検索', class:'sp-search__btn' %>
    <% end %>
  </div>
  <% if @search_result.present? %>
    <h2 class='sp-search__result'>
      検索結果{ <%= @search_result.total_count %>件 }
    </h2>
    <h3 class='sp-search__text'>
      <%= @search_result.current_page %>/<%= @search_result.total_pages %>ページ
    </h3>
    <div class='sp-list-box'>
      <%= render partial: 'posts/partial/sp-index', collection: @search_result, as: :post %>
    </div>
    <div class='sp-search__paginate'>
      <%= paginate @search_result %>
    </div>
  <% elsif @search_result == [] %>
    <h2 class='sp-search__result'>該当する投稿が見つかりません。</h2>
  <% else %>
      <h2 class='sp-search__result'>キーワードを入力して下さい</h2>
  <% end %>
  <%= render 'layouts/shared/sp-button' %>
  <%= render 'layouts/shared/sp-banner' %>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post_show_title) %>
<main>
<%= render 'layouts/shared/header' %>
<%= render 'layouts/shared/flash' %>
<%= render 'layouts/shared/validation-message' %>
  <div class='detail-post-box'>
    <div class='user-info'>
      <%= link_to @post.user do %>
        <%= meshi_show_user_image(@post) %>
      <% end %>
      <div class='user-info__name'>
        <%= @post.user.nickname %>
      </div>
    </div>
    <div class='detail-container'>
      <div class='detail-container__name'>
        <%= @post.name %>
        <%= render 'likes/like-links', post: @post %>
      </div>
        <%= post_show_image(@post) %>
      <h2>山の詳細データ</h2>
      <div class='detail-description'>
        <div class='detail-description__display'>
          山頂標高:<%= @post.elevation %>M
        </div>
        <div class='detail-description__display'>
          歩行距離:<%= @post.walking_distance %>KM
        </div>
        <div class='detail-description__display'>
          <%= @post.difficulty_i18n %>
        </div>
        <div class='detail-description__display'>
          <%= @post.prefecture.name %>
        </div>
      </div>
      <h2><%= @post.user.nickname %>さんのコメント</h2>
      <div class='detail-description__display'>
        <%= simple_format(@post.text) %>
      </div>

      <%= render 'comments/partial/comment' %>

      <% if signed_in_and_current_user_comment? %>
        <div class='detail-btn'>
          <%= link_to 'ホーム', root_path, class:'detail-btn__gray' %>
          <%= link_to '編集', edit_post_path(@post), method: :get, class:'detail-btn__gray' %>
        </div>
        <%= link_to post_path(@post), method: :delete, data: { confirm: "本当に削除しますか?" } do %>
          <button class='delete-btn'>削除する</button>
        <% end %>
      <% else %>
        <div class='detail-btn'>
          <%= link_to 'ホーム', root_path, class:'detail-btn__gray' %>
        </div>
      <% end %>
    </div>
  </div>
  <%= render 'layouts/shared/footer' %>
</main>

<%# スマホ用詳細ページ %>
<div class='sp-main'>
  <%= render 'layouts/shared/sp-header' %>
  <div class='sp-detail'>
    <div class='sp-detail__user'>
      <%= link_to @post.user do %>
        <%= sp_post_circle_user_image(@post) %>
      <% end %>
      <div class='sp-detail__user__nickname'><%= @post.user.nickname %></div>
    </div>
    <div class='sp-detail__post-name'>
      <%= @post.name %>
    </div>
    <div class='sp-detail__pic-box'>
      <%= sp_show_image(@post) %>
    </div>
    <i class='far fa-heart fa-2x'>
      <span><%= @post.likes.count %></span>
    </i>
    <%= link_to post_comment_path(@post) do %>
      <i class='far fa-comment fa-2x'>
        <span><%= @post.comments.count %></span>
      </i>
    <% end %>
    <% if signed_in_and_current_user_comment? %>
      <%= link_to edit_post_path(@post), method: :get, class:'sp-detail__btn' do %>
        <i class='far fa-edit fa-2x'></i>
      <% end %>
      <%= link_to post_path(@post), method: :delete, class:'sp-detail__btn', data: { confirm: "本当に削除しますか?" } do %>
        <i class='far fa-trash-alt fa-2x'></i>
      <% end %>
    <% end %>
    <h2 class='sp-detail__title'>山のデータ</h2>
    <div class='sp-detail__description'>
      <div class='sp-detail__description__name'>
        山頂標高:
        <div class='sp-detail__description__count'>
          <%= @post.elevation %>M
        </div>
      </div>
      <div class='sp-detail__description__name'>
        歩行距離:
        <div class='sp-detail__description__count'>
          <%= @post.walking_distance %>KM
        </div>
      </div>
      <div class='sp-detail__description__name'>
        <%= @post.prefecture.name %><br/>
        <%= @post.difficulty_i18n %>
      </div>
    </div>
    <div class='sp-detail__comment__box'>
      <h3 class='sp-detail__comment__box__text'>
        <%= simple_format(@post.text) %>
      </h3>
    </div>
    <%= render 'comments/shared/sp-comment-list' %>
    <% if current_user %>
      <div class='sp-new-comment-box''>
        <%= form_for [@post, @comment] do |f| %>
          <%= f.text_area :text, class:'sp-new-comment-box__form' %>
          <%= f.submit 'コメントする', class:'sp-new-comment__btn' %>
        <% end %>
      </div>
    <% else %>
      <%= link_to 'ログインしてコメントしよう！', new_user_session_path, class:'sp-comment-login-link' %>
    <% end %>
  </div>
  <%= render "layouts/shared/sp-banner" %>
</div>

app/views/posts/tab.html.erb
<main>
  <%= render 'layouts/shared/header' %>
  <div class='nav-bar'>
    このサイトについて
  </div>
  <div class='container'>
    <ul class='menu'>
      <li><a href='#' id='about' class='menu_item active'>このアプリについて</a></li>
      <li><a href='#' id='service' class='menu_item'>使い方</a></li>
      <li><a href='#' id='contact' class='menu_item'>お知らせ</a></li>
    </ul>
    <ul class='contents'>
      <li class='content show'>
        <%= render 'posts/partial/pc-about' %>
      </li>
      <li class='content'>
        <%=render 'posts/partial/pc-usage' %>
      </li>
      <li class='content'>
        <%= render 'posts/partial/pc-notification' %>
      </li>
    </ul>
  </div>
  <%= render 'layouts/shared/footer' %>
</main>

app/views/posts/usage.html.erb
<% provide(:title, "使い方") %>
<div class="sp-main">
  <div class="detail-post-box">
    <div class="detail-post-container">
      <div class="detail-name">
        アプリの使い方
      </div>
      <h2>ログイン</h2>
      <div class="detail-description">
        <div class="detail-display">
          テストユーザーが登録されています。トップページ上段右マイページボックス内の「ログイン」ボタンを押して<br/>email「 user1@example.com 」<br/>password「 password 」<br/>と入力するとログインできます。
        </div>
      </div>
      <h2>ログアウト</h2>
      <div class="detail-description">
        <div class="detail-display">
          マイページボックス上の「ログアウト」ボタンを押すとログアウトできます。
        </div>
      </div>
      <h2>ユーザー新規登録</h2>
      <div class="detail-description">
        <div class="detail-display">
          未ログイン状態で「新規登録」ボタンを押すと会員登録画面へ遷移します。メールアドレス、ニックネーム、パスワードを入力して下さい。プロフィールとプロフィール画像は任意です。「登録する」ボタンを押して新規登録できます。
        </div>
      </div>
      <h2>ユーザー情報編集</h2>
      <div class="detail-description">
        <div class="detail-display">
          マイページボックス上の「プロフィール変更」を押すとユーザー情報編集ページに遷移します。変更したい項目を入力し現在のパスワードを入力して下さい。「更新する」ボタンを押すとプロフィールが更新されます。
        </div>
      </div>
      <h2>投稿</h2>
      <div class="detail-description">
        <div class="detail-display">
          ログインすると投稿できるようになります。マイページボックス内の「投稿」ボタンを押すと入力画面に遷移します。必要項目(必須)を入力し「投稿する」ボタンを押せば投稿した内容がトップページに表示されます。
        </div>
      </div>
      <h2>投稿一覧</h2>
      <div class="detail-description">
        <div class="detail-display">
          他ユーザーの投稿は画面左上の「最新投稿」内に表示されます。詳しい内容を確認するには該当の投稿をクリックして下さい。詳細画面では「いいね」と「コメント」機能が使えます。いいねはハートマークをクリックすれば反映されます。コメント機能は「コメントを書く」内のフォームに入力し「コメントする」を押せば反映されます。
        </div>
      </div>
      <h2>ユーザー 一覧</h2>
      <div class="detail-description">
        <div class="detail-display">
          「ユーザー一覧」が画面上中央に表示されています。詳しい内容を確認するには該当のユーザーをクリックして下さい。ユーザー詳細画面にはユーザーの投稿一覧の表示と「フォロー」機能が使えます。フォローしている人数・されている人数はトップページのマイページボックスにて確認できます。
        </div>
      </div>
      <h2>検索機能</h2>
      <div class="detail-description">
        <div class="detail-display">
          画面右上の検索窓で投稿されている山の名前とコメントを検索できます。例）「テスト山」と入力し「検索」ボタンを押すと「テスト山」を含む投稿が検索されます。
        </div>
      </div>
      <h2>ランキング機能</h2>
      <div class="detail-description">
        <div class="detail-display">
          トップ画面中段に人気投稿ランキングがあります。いいねの数に応じてTOP5の投稿が表示されます。
        </div>
      </div>
    </div>
  </div>
</div>